config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  
  resources :products
  resources :users do
    resources :products
  end
  resources :products do
    post 'add_to_cart', on: :member
  end
  resource :cart, only: [:show]
  resources :cart_items, only: [:destroy, :update]
  resources :orders

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  

  # Defines the root path route ("/")
  # root "posts#index"
  root to: "home#index" 

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :cart_items, dependent: :destroy

  def add_item(product, quantity)
    current_item = cart_items.find_by(product: product)

    if current_item
      current_item.quantity += quantity
    else
      current_item = cart_items.build(product: product, quantity: quantity)
    end

    current_item.save
  end
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :product
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_items, dependent: :destroy

  enum status: { pending: 0, processing: 1, confirmed: 2, shipped: 3, delivered: 4, canceled: 5 }
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
  has_one_attached :image
  has_many :cart_items
  has_many :order_items
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_one :cart
  has_many :orders

  # Roles
  CUSTOMER = 0
  ADMIN = 1

  def admin?
    role == ADMIN
  end

  # TODO: check this before commit
  def cart
    super || create_cart
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit::Authorization

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def user_not_authorized
    flash[:alert] = 'You are not authorized to perform this action.'
    # redirect_to root_path
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  before_action :authenticate_user!

  def destroy
    @cart_item = CartItem.find(params[:id])
    if @cart_item.destroy
      redirect_to cart_path, notice: 'Product removed from the cart.'
    else
      flash[:alert] = 'Failed to delete.'
      redirect_to cart_path
    end
  end
  
  def update
    @cart_item = CartItem.find(params[:id])
    if params[:operation] == 'increase'
      @cart_item.quantity += 1
      if @cart_item.save
        redirect_to
      end
    else
      @cart_item.quantity -= 1
      if @cart_item.quantity == 0
        @cart_item.destroy!
        redirect_to
      else
        @cart_item.save
          redirect_to
      end
    end
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!

  def show
    @cart = current_user.cart
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    render
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  include OrdersHelper
  before_action :authenticate_user!

  def index
    @orders = Order.all
  end

  def create
    @cart = current_user.cart
    order_params = {
      user: current_user,
      invoice_number: generate_invoice_number,
      total_price: get_cart_total_price
    }
    @order = Order.create(order_params)
    move_cart_items_to_order(@order)
    if @order.save
      redirect_to order_path(@order), notice: 'Order placed successfully.'
    else
      redirect_to cart_path, alert: 'Error placing the order.'
    end
  end

  def show
    begin
      @order = Order.find(params[:id])
    rescue
      redirect_to orders_path
    end
  end  

  def update
    @order = Order.find(params[:id])
    new_status = params[:order][:status]&.to_sym
    if new_status && @order.update(status: new_status)
      redirect_to order_path(@order), notice: "Order status updated to #{new_status.capitalize}."
    else
      redirect_to order_path(@order), alert: 'Error updating order status.'
    end
  end

  def destroy
    authorize @order
    @order = Order.find(params[:id])
    if @order.destroy
      redirect_to orders_path, notice: 'Order deleted successfully.'
    else
      redirect_to orders_path, notice: 'Something went wrong!'
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy, :add_to_cart]
  # before_action :authenticate_admin!, except: [:index, :show]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /products
  # def index
  #   @products = Product.all
  #   # authorize @products
  # end
  def index
    respond_to do |format|
      format.html
      format.json { render json: ProductDatatable.new(params) }
    end
  end
  
  # GET /products/1
  def show
  end
  
  # GET /products/new
  def new
    @product = Product.new
    authorize @product
  end
  
  # GET /products/1/edit
  def edit
    authorize @product
  end
  
  # POST /products
  def create
    @product = Product.new(product_params)
    authorize @product
    if @product.save
      redirect_to @product, notice: 'Product was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /products/1
  def update
    authorize @product
    if @product.update(product_params)
      redirect_to @product, notice: 'Product was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /products/1
  def destroy
    authorize @product
    if @product.destroy
      redirect_to products_url, notice: 'Product was successfully deleted.'
    else
      redirect_to products_url, notice: 'Something went wrong!'
    end
  end

  # Add product to cart
  def add_to_cart
    quantity = params[:quantity].to_i
    if current_user.cart.add_item(@product, quantity)
      redirect_to @product, notice: 'Product added to cart successfully.'
    else
      redirect_to @product, notice: 'Something went wrong!'
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_product
    @product = Product.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def product_params
    params.require(:product).permit(:name, :description, :price, :in_stock, :image)
  end

  # Check if the user is an admin
  def authenticate_admin!
    unless current_user&.admin?
      flash[:alert] = 'You are not authorized to perform this action.'
      redirect_to products_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
  def generate_invoice_number
    # Logic to generate a unique invoice number, e.g., using timestamp
    Time.now.strftime('%Y%m%d%H%M%S')
  end

  def move_cart_items_to_order(order)
    order_items = []
    @cart.cart_items.each do |cart_item|
      order_items << {
        order_id: @order.id,
        product_id: cart_item.product.id,
        quantity: cart_item.quantity
    }
    end
    OrderItem.create(order_items)
    @cart.cart_items.destroy_all    
  end
  
  # get total price of cart
  def get_cart_total_price
    @cart.cart_items.sum {|item| item.quantity * item.product.price}
  end

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/carts/show.html.erb
<h1>My Cart</h1>
<% if !@cart.cart_items.present? %>
  <p>Your cart is empty.</p>
  <%= link_to 'Continue Shopping', products_path, class: 'btn btn-primary' %>
<% else %>
  <table class="table">
    <thead>
      <tr>
        <th>Product</th>
        <th>Image</th>
        <th>Quantity</th>
        <th>Price</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @cart.cart_items.each do |item| %>
        <tr>
          <td><%= item.product.name %></td>
          <td>
            <img class="rounded-circle" width="55" <%=image_tag(item.product.image)%>
          </td>
            <td>
              <div class="d-flex align-items-baseline">
                <div>
                  <%= button_to '-', cart_item_path(item.id, operation: 'decrease'), method: :patch, class: "btn btn-outline-secondary" %>
                </div>
                <div>
                  &nbsp; <%= item.quantity %> &nbsp;
                </div>
                <div>
                  <%= button_to '+', cart_item_path(item.id, operation: 'increase'), method: :patch, class: "btn btn-outline-secondary" %>
                </div>
              </div>
            </td>
            <td><%= item.product.price %></td>
            <td>
              <%= link_to 'Remove', item, data: { turbo_method: :delete, confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm' %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <div class="d-flex">
      <div>
        <%= link_to 'Continue Shopping', products_path, class: 'btn btn-primary me-2' %>
      </div>
      <div>
        <%= button_to 'Place Order', orders_path, method: :post, class: 'btn btn-success' %>
      </div>
    </div>
  <% end %>

app/views/custom/_header.html.erb
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">ZipKart</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/products">Products</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/orders">Orders</a>
        </li>
      </ul>

      <!-- Cart icon -->
      <a class="navbar-brand position-relative me-5" href="/cart">
        <img src="https://www.freepnglogos.com/uploads/shopping-cart-png/shopping-cart-svg-png-icon-download-28.png" alt="Logo" width="26" height="20" class="d-inline-block align-text-center">
        <!-- Cart Item count -->
        <% if current_user&.cart&.cart_items&.length %>
          <span class="position-absolute start-100 top-10 translate-middle badge rounded-pill bg-danger">
            <%= current_user&.cart&.cart_items&.length %>
            <span class="visually-hidden">unread messages</span>
        </span>
        <% end %>
      </a>

      <!-- Avatar -->
      <% if user_signed_in? %> 
      <div class="dropdown">
        <a class="dropdown-toggle d-flex align-items-center hidden-arrow" href="#" role="button" id="avatarDropdown" data-bs-toggle="dropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <img
            src="https://mdbcdn.b-cdn.net/img/new/avatars/2.webp"
            class="rounded-circle"
            height="25"
            alt="Black and White Portrait of a Man"
            loading="lazy"
          />
        </a>
        <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="avatarDropdown">
          <li>
            <span class="dropdown-item"><%= current_user.email %></span>
          </li>
          <li>
            <%= link_to "Sign out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %> 
          </li>
        </ul>
      </div>
      <% else %>
          <%= button_to "Sign in", new_user_session_path, class: "btn btn-outline-success"%> 
      <% end %>
    </div>
  </div>
</nav>

app/views/home/index.html.erb
<h1>Hello Home Page!</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ZipKart</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= render 'custom/header' %>
    <% if notice %>
      <p class="notice"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert"><%= alert %></p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/orders/index.html.erb
<div class="container mt-4">
  <% if current_user.admin? %>
    <h1>All Orders</h1>
  <% else %>
    <h1>My Orders</h1>
  <% end  %>
  <% if @orders.present? %>
    <div class="container">
      <div class="row">
        <div class="col">
          <table class="table table-striped table-hover table-sm">
            <thead>
              <tr>
                <th scope="col">Invoice Number</th>
                <th scope="col">Total Price</th>
                <th scope="col">Action</th>
              </tr>
            </thead>
            <tbody>
              <% @orders.each do |order| %>
                <tr>
                  <td><%= order.invoice_number %></td>
                  <td><%= number_to_currency(order.total_price) %></td>
                  <td>
                    <div class='d-flex'>
                      <div>
                        <%= link_to 'View', order_path(order), class: 'btn btn-primary btn-sm' %>
                      </div>
                      <%= button_to 'Delete', order, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm ms-2' %>
                    </div>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  <% else %>
    <p>No orders available.</p>
  <% end %>
  <%= link_to 'Back to Home', root_path, class: 'btn btn-secondary mt-3' %>
</div>

app/views/orders/show.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="col">
      <h1>Order Details</h1>
      <p><strong>Invoice Number:</strong> <%= @order.invoice_number %></p>
      <p><strong>Total Price: <%= number_to_currency(@order.total_price) %></strong></p>
      <!-- Add other order details here -->
      <h2>Order Items</h2>
      <% if @order.order_items.length %>
        <ul class="list-group">
          <% @order.order_items.each do |item| %>
            <li class="list-group-item">
              <strong><%= item.product.name %></strong>
              <p><strong>Description:</strong> <%= item.product.description %></p>
              <p><strong>Price per Unit:</strong> <%= number_to_currency(item.product.price) %></p>
              <p><strong>Quantity:</strong> <%= item.quantity %></p>
              <p><strong>Status :</strong> <%=  @order.status %></p>
            </li>
          <% end %>
        </ul>
      <% else %>
        <p>No items in this order.</p>
      <% end %>
      <% if current_user&.admin?  %>
        <%= form_with(model: @order, url: order_path(@order), method: :patch, class: 'mb-3') do |form| %>
          <div class="mb-3">
            <%= form.label :status, class: 'form-label' %>
            <%= form.select :status, Order.statuses.keys.map { |s| [s.capitalize, s] }, class: 'form-select' %>
          </div>
          <%= form.submit 'Update Status', class: 'btn btn-primary' %>
        <% end %>
        <%= button_to 'Delete Order', @order, method: :delete, class: 'd-inline btn btn-danger mt-3' %>
      <% else %>
        <%= button_to 'Cancel Order', @order, method: :delete, class: 'btn btn-danger mt-3' %>
      <% end %>
      <%= link_to 'Back to Orders', orders_path, class: 'btn btn-primary mt-3' %>
    </div>
  </div>
</div>

app/views/orders/update.html.erb
<div class="container mt-4">
  <h1>Update Order Status</h1>
  <%= form_with(model: @order, url: update_status_order_path(@order), method: :patch, class: 'mb-3') do |form| %>
    <div class="mb-3">
      <%= form.label :status, class: 'form-label' %>
      <%= form.select :status, Order.statuses.keys.map { |s| [s.capitalize, s] }, class: 'form-select' %>
    </div>
    <%= form.submit 'Update Status', class: 'btn btn-primary' %>
  <% end %>
  <%= link_to 'Back to Order', order_path(@order), class: 'btn btn-secondary mt-3' %>
</div>

app/views/products/_form.html.erb
<%= form_with(model: @product, local: true) do |form| %>
  <div class="mb-3">
    <%= form.label :name, class: 'form-label' %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>
  <div class="mb-3">
    <%= form.label :description, class: 'form-label' %>
    <%= form.text_area :description, class: 'form-control' %>
  </div>
  <div class="mb-3">
    <%= form.label :price, class: 'form-label' %>
    <%= form.number_field :price, class: 'form-control' %>
  </div>
  <div class="mb-3">
    <%= form.label :in_stock, class: 'form-check-label' %>
    <%= form.check_box :in_stock, class: 'form-check-input' %>
  </div>
  <div class="mb-3">
    <%= form.label :image, class: 'form-label' %>
    <%= form.file_field :image, class: 'form-control' %>
  </div>
  <div class="mb-3">
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/products/create.html.erb
<h1>Products#create</h1>
<p>Find me in app/views/products/create.html.erb</p>

app/views/products/destroy.html.erb
<h1>Products#destroy</h1>
<p>Find me in app/views/products/destroy.html.erb</p>

app/views/products/edit.html.erb
<h1>Edit Product</h1>
<%= render 'form' %>
<%= link_to 'Show', @product, class: 'btn btn-primary' %>
<%= link_to 'Back', products_path, class: 'btn btn-secondary' %>

app/views/products/index.html.erb
<link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.3.0/css/bootstrap.min.css" rel="stylesheet">
<link href="https://cdn.datatables.net/v/bs5/jq-3.7.0/dt-1.13.6/b-2.4.2/r-2.5.0/datatables.min.css" rel="stylesheet">
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.3.0/js/bootstrap.bundle.min.js"></script>
<script src="https://cdn.datatables.net/v/bs5/jq-3.7.0/dt-1.13.6/b-2.4.2/r-2.5.0/datatables.min.js"></script>
<table id="product-datatable" data-source="<%= products_path(format: :json) %>">
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
    </tr>
  </thead>
  <tbody>
  </tbody>
</table>
<script>
  $(document).ready(function() {
  $('#product-datatable').DataTable({
    "processing": true,
    "serverSide": true,
    "ajax": {
    "url": $('#product-datatable').data('source')
    },
    "pagingType": "full_numbers",
    "columns": [
    {"data": "id"},
    {"data": "name"},
    {"data": "description"},
    {"data": "price"}
    ]
    // pagingType is optional, if you want full pagination controls.
    // Check dataTables documentation to learn more about
    // available options.
  });
  });
</script>

app/views/products/new.html.erb
<h1>New Product</h1>
<%= render 'form' %>
<%= link_to 'Back', products_path, class: 'btn btn-secondary' %>

app/views/products/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col d-flex justify-content-center'>
      <div class="card m-3 shadow" style="max-width: 720px;">
        <div class="row g-0">
          <div class="col-md-4">
            <% if @product.image.attached? %>
              <p>
              <%= image_tag @product.image, class: "img-fluid rounded-start" %>
              </p>
            <% else %>
            <img
              src="https://www.mahalaxmifoods.com/include/assets/default_product_image.png"
              alt="Default product image"
              class="img-fluid rounded-start"
            />
            <% end %>
          </div>
          <div class="col-md-8">
            <div class="card-body">
              <h5 class="card-title"><%= @product.name %></h5>
              <p class="card-text text-muted mb-2">
                <strong>Description: </strong> <br>
                <%= @product.description[0,650] + "..." %>
              </p>
              <p class="card-text mb-2">
                <strong>Stock: </strong>
                <%= @product.in_stock ? 'Available' : 'Currently unavailable' %>
              </p>
              <% if current_user&.admin?  %>
                <%= link_to 'Edit', edit_product_path(@product), class: 'btn btn-warning' %>
              <% else %>
                <%= form_with(url: add_to_cart_product_path(@product), method: :post, class: '') do |form| %>
                  <%= form.hidden_field :quantity, value: 1 %>
                  <%= form.submit 'Add to Cart', class: 'btn btn-success' %>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/products/update.html.erb
<h1>Products#update</h1>
<p>Find me in app/views/products/update.html.erb</p>